/* automatically generated by rust-bindgen 0.72.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub const SQTrue: u32 = 1;
    pub const SQFalse: u32 = 0;
    pub const SQ_ALIGNMENT: u32 = 8;
    pub const MAX_CHAR: u32 = 255;
    pub const SQUIRREL_VERSION_NUMBER: u32 = 320;
    pub const SQ_VMSTATE_IDLE: u32 = 0;
    pub const SQ_VMSTATE_RUNNING: u32 = 1;
    pub const SQ_VMSTATE_SUSPENDED: u32 = 2;
    pub const SQUIRREL_EOB: u32 = 0;
    pub const SQ_BYTECODE_STREAM_TAG: u32 = 64250;
    pub const SQOBJECT_REF_COUNTED: u32 = 134217728;
    pub const SQOBJECT_NUMERIC: u32 = 67108864;
    pub const SQOBJECT_DELEGABLE: u32 = 33554432;
    pub const SQOBJECT_CANBEFALSE: u32 = 16777216;
    pub const SQ_MATCHTYPEMASKSTRING: i32 = -99999;
    pub const _RT_MASK: u32 = 16777215;
    pub const _RT_NULL: u32 = 1;
    pub const _RT_INTEGER: u32 = 2;
    pub const _RT_FLOAT: u32 = 4;
    pub const _RT_BOOL: u32 = 8;
    pub const _RT_STRING: u32 = 16;
    pub const _RT_TABLE: u32 = 32;
    pub const _RT_ARRAY: u32 = 64;
    pub const _RT_USERDATA: u32 = 128;
    pub const _RT_CLOSURE: u32 = 256;
    pub const _RT_NATIVECLOSURE: u32 = 512;
    pub const _RT_GENERATOR: u32 = 1024;
    pub const _RT_USERPOINTER: u32 = 2048;
    pub const _RT_THREAD: u32 = 4096;
    pub const _RT_FUNCPROTO: u32 = 8192;
    pub const _RT_CLASS: u32 = 16384;
    pub const _RT_INSTANCE: u32 = 32768;
    pub const _RT_WEAKREF: u32 = 65536;
    pub const _RT_OUTER: u32 = 131072;
    pub const SQ_OK: u32 = 0;
    pub const SQ_ERROR: i32 = -1;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQVM {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQTable {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQArray {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQString {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQClosure {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQGenerator {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQNativeClosure {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQUserData {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQFunctionProto {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQRefCounted {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQClass {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQInstance {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQDelegable {
        _unused: [u8; 0],
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQOuter {
        _unused: [u8; 0],
    }
    pub type SQInteger = ::std::os::raw::c_longlong;
    pub type SQUnsignedInteger = ::std::os::raw::c_ulonglong;
    pub type SQHash = ::std::os::raw::c_ulonglong;
    pub type SQInt32 = ::std::os::raw::c_int;
    pub type SQUnsignedInteger32 = ::std::os::raw::c_uint;
    pub type SQFloat = f32;
    pub type SQRawObjectVal = ::std::os::raw::c_longlong;
    pub type SQUserPointer = *mut ::std::os::raw::c_void;
    pub type SQBool = root::SQUnsignedInteger;
    pub type SQRESULT = root::SQInteger;
    pub type SQChar = ::std::os::raw::c_char;
    pub const tagSQObjectType_OT_NULL: tagSQObjectType = 16777217;
    pub const tagSQObjectType_OT_INTEGER: tagSQObjectType = 83886082;
    pub const tagSQObjectType_OT_FLOAT: tagSQObjectType = 83886084;
    pub const tagSQObjectType_OT_BOOL: tagSQObjectType = 16777224;
    pub const tagSQObjectType_OT_STRING: tagSQObjectType = 134217744;
    pub const tagSQObjectType_OT_TABLE: tagSQObjectType = 167772192;
    pub const tagSQObjectType_OT_ARRAY: tagSQObjectType = 134217792;
    pub const tagSQObjectType_OT_USERDATA: tagSQObjectType = 167772288;
    pub const tagSQObjectType_OT_CLOSURE: tagSQObjectType = 134217984;
    pub const tagSQObjectType_OT_NATIVECLOSURE: tagSQObjectType = 134218240;
    pub const tagSQObjectType_OT_GENERATOR: tagSQObjectType = 134218752;
    pub const tagSQObjectType_OT_USERPOINTER: tagSQObjectType = 2048;
    pub const tagSQObjectType_OT_THREAD: tagSQObjectType = 134221824;
    pub const tagSQObjectType_OT_FUNCPROTO: tagSQObjectType = 134225920;
    pub const tagSQObjectType_OT_CLASS: tagSQObjectType = 134234112;
    pub const tagSQObjectType_OT_INSTANCE: tagSQObjectType = 167804928;
    pub const tagSQObjectType_OT_WEAKREF: tagSQObjectType = 134283264;
    pub const tagSQObjectType_OT_OUTER: tagSQObjectType = 134348800;
    pub type tagSQObjectType = ::std::os::raw::c_int;
    pub use self::super::root::tagSQObjectType as SQObjectType;
    #[repr(C)]
    #[derive(Copy, Clone)]
    pub union tagSQObjectValue {
        pub pTable: *mut root::SQTable,
        pub pArray: *mut root::SQArray,
        pub pClosure: *mut root::SQClosure,
        pub pOuter: *mut root::SQOuter,
        pub pGenerator: *mut root::SQGenerator,
        pub pNativeClosure: *mut root::SQNativeClosure,
        pub pString: *mut root::SQString,
        pub pUserData: *mut root::SQUserData,
        pub nInteger: root::SQInteger,
        pub fFloat: root::SQFloat,
        pub pUserPointer: root::SQUserPointer,
        pub pFunctionProto: *mut root::SQFunctionProto,
        pub pRefCounted: *mut root::SQRefCounted,
        pub pDelegable: *mut root::SQDelegable,
        pub pThread: *mut root::SQVM,
        pub pClass: *mut root::SQClass,
        pub pInstance: *mut root::SQInstance,
        pub pWeakRef: *mut root::SQWeakRef,
        pub raw: root::SQRawObjectVal,
    }
    #[allow(clippy::unnecessary_operation, clippy::identity_op)]
    const _: () = {
        ["Size of tagSQObjectValue"][::std::mem::size_of::<tagSQObjectValue>() - 8usize];
        ["Alignment of tagSQObjectValue"][::std::mem::align_of::<tagSQObjectValue>() - 8usize];
        ["Offset of field: tagSQObjectValue::pTable"]
            [::std::mem::offset_of!(tagSQObjectValue, pTable) - 0usize];
        ["Offset of field: tagSQObjectValue::pArray"]
            [::std::mem::offset_of!(tagSQObjectValue, pArray) - 0usize];
        ["Offset of field: tagSQObjectValue::pClosure"]
            [::std::mem::offset_of!(tagSQObjectValue, pClosure) - 0usize];
        ["Offset of field: tagSQObjectValue::pOuter"]
            [::std::mem::offset_of!(tagSQObjectValue, pOuter) - 0usize];
        ["Offset of field: tagSQObjectValue::pGenerator"]
            [::std::mem::offset_of!(tagSQObjectValue, pGenerator) - 0usize];
        ["Offset of field: tagSQObjectValue::pNativeClosure"]
            [::std::mem::offset_of!(tagSQObjectValue, pNativeClosure) - 0usize];
        ["Offset of field: tagSQObjectValue::pString"]
            [::std::mem::offset_of!(tagSQObjectValue, pString) - 0usize];
        ["Offset of field: tagSQObjectValue::pUserData"]
            [::std::mem::offset_of!(tagSQObjectValue, pUserData) - 0usize];
        ["Offset of field: tagSQObjectValue::nInteger"]
            [::std::mem::offset_of!(tagSQObjectValue, nInteger) - 0usize];
        ["Offset of field: tagSQObjectValue::fFloat"]
            [::std::mem::offset_of!(tagSQObjectValue, fFloat) - 0usize];
        ["Offset of field: tagSQObjectValue::pUserPointer"]
            [::std::mem::offset_of!(tagSQObjectValue, pUserPointer) - 0usize];
        ["Offset of field: tagSQObjectValue::pFunctionProto"]
            [::std::mem::offset_of!(tagSQObjectValue, pFunctionProto) - 0usize];
        ["Offset of field: tagSQObjectValue::pRefCounted"]
            [::std::mem::offset_of!(tagSQObjectValue, pRefCounted) - 0usize];
        ["Offset of field: tagSQObjectValue::pDelegable"]
            [::std::mem::offset_of!(tagSQObjectValue, pDelegable) - 0usize];
        ["Offset of field: tagSQObjectValue::pThread"]
            [::std::mem::offset_of!(tagSQObjectValue, pThread) - 0usize];
        ["Offset of field: tagSQObjectValue::pClass"]
            [::std::mem::offset_of!(tagSQObjectValue, pClass) - 0usize];
        ["Offset of field: tagSQObjectValue::pInstance"]
            [::std::mem::offset_of!(tagSQObjectValue, pInstance) - 0usize];
        ["Offset of field: tagSQObjectValue::pWeakRef"]
            [::std::mem::offset_of!(tagSQObjectValue, pWeakRef) - 0usize];
        ["Offset of field: tagSQObjectValue::raw"]
            [::std::mem::offset_of!(tagSQObjectValue, raw) - 0usize];
    };
    pub type SQObjectValue = root::tagSQObjectValue;
    #[repr(C)]
    #[derive(Copy, Clone)]
    pub struct tagSQObject {
        pub _type: root::SQObjectType,
        pub _unVal: root::SQObjectValue,
    }
    #[allow(clippy::unnecessary_operation, clippy::identity_op)]
    const _: () = {
        ["Size of tagSQObject"][::std::mem::size_of::<tagSQObject>() - 16usize];
        ["Alignment of tagSQObject"][::std::mem::align_of::<tagSQObject>() - 8usize];
        ["Offset of field: tagSQObject::_type"]
            [::std::mem::offset_of!(tagSQObject, _type) - 0usize];
        ["Offset of field: tagSQObject::_unVal"]
            [::std::mem::offset_of!(tagSQObject, _unVal) - 8usize];
    };
    pub type SQObject = root::tagSQObject;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct tagSQMemberHandle {
        pub _static: root::SQBool,
        pub _index: root::SQInteger,
    }
    #[allow(clippy::unnecessary_operation, clippy::identity_op)]
    const _: () = {
        ["Size of tagSQMemberHandle"][::std::mem::size_of::<tagSQMemberHandle>() - 16usize];
        ["Alignment of tagSQMemberHandle"][::std::mem::align_of::<tagSQMemberHandle>() - 8usize];
        ["Offset of field: tagSQMemberHandle::_static"]
            [::std::mem::offset_of!(tagSQMemberHandle, _static) - 0usize];
        ["Offset of field: tagSQMemberHandle::_index"]
            [::std::mem::offset_of!(tagSQMemberHandle, _index) - 8usize];
    };
    pub type SQMemberHandle = root::tagSQMemberHandle;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct tagSQStackInfos {
        pub funcname: *const root::SQChar,
        pub source: *const root::SQChar,
        pub line: root::SQInteger,
    }
    #[allow(clippy::unnecessary_operation, clippy::identity_op)]
    const _: () = {
        ["Size of tagSQStackInfos"][::std::mem::size_of::<tagSQStackInfos>() - 24usize];
        ["Alignment of tagSQStackInfos"][::std::mem::align_of::<tagSQStackInfos>() - 8usize];
        ["Offset of field: tagSQStackInfos::funcname"]
            [::std::mem::offset_of!(tagSQStackInfos, funcname) - 0usize];
        ["Offset of field: tagSQStackInfos::source"]
            [::std::mem::offset_of!(tagSQStackInfos, source) - 8usize];
        ["Offset of field: tagSQStackInfos::line"]
            [::std::mem::offset_of!(tagSQStackInfos, line) - 16usize];
    };
    pub type SQStackInfos = root::tagSQStackInfos;
    pub type HSQUIRRELVM = *mut root::SQVM;
    pub type HSQOBJECT = root::SQObject;
    pub type HSQMEMBERHANDLE = root::SQMemberHandle;
    pub type SQFUNCTION =
        ::std::option::Option<unsafe extern "C" fn(arg1: root::HSQUIRRELVM) -> root::SQInteger>;
    pub type SQRELEASEHOOK = ::std::option::Option<
        unsafe extern "C" fn(arg1: root::SQUserPointer, size: root::SQInteger) -> root::SQInteger,
    >;
    pub type SQCOMPILERERROR = ::std::option::Option<
        unsafe extern "C" fn(
            arg1: root::HSQUIRRELVM,
            arg2: *const root::SQChar,
            arg3: *const root::SQChar,
            arg4: root::SQInteger,
            arg5: root::SQInteger,
        ),
    >;
    pub type SQPRINTFUNCTION = ::std::option::Option<
        unsafe extern "C" fn(arg1: root::HSQUIRRELVM, arg2: *const root::SQChar, ...),
    >;
    pub type SQDEBUGHOOK = ::std::option::Option<
        unsafe extern "C" fn(
            arg1: root::HSQUIRRELVM,
            arg2: root::SQInteger,
            arg3: *const root::SQChar,
            arg4: root::SQInteger,
            arg5: *const root::SQChar,
        ),
    >;
    pub type SQWRITEFUNC = ::std::option::Option<
        unsafe extern "C" fn(
            arg1: root::SQUserPointer,
            arg2: root::SQUserPointer,
            arg3: root::SQInteger,
        ) -> root::SQInteger,
    >;
    pub type SQREADFUNC = ::std::option::Option<
        unsafe extern "C" fn(
            arg1: root::SQUserPointer,
            arg2: root::SQUserPointer,
            arg3: root::SQInteger,
        ) -> root::SQInteger,
    >;
    pub type SQLEXREADFUNC =
        ::std::option::Option<unsafe extern "C" fn(arg1: root::SQUserPointer) -> root::SQInteger>;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct tagSQRegFunction {
        pub name: *const root::SQChar,
        pub f: root::SQFUNCTION,
        pub nparamscheck: root::SQInteger,
        pub typemask: *const root::SQChar,
    }
    #[allow(clippy::unnecessary_operation, clippy::identity_op)]
    const _: () = {
        ["Size of tagSQRegFunction"][::std::mem::size_of::<tagSQRegFunction>() - 32usize];
        ["Alignment of tagSQRegFunction"][::std::mem::align_of::<tagSQRegFunction>() - 8usize];
        ["Offset of field: tagSQRegFunction::name"]
            [::std::mem::offset_of!(tagSQRegFunction, name) - 0usize];
        ["Offset of field: tagSQRegFunction::f"]
            [::std::mem::offset_of!(tagSQRegFunction, f) - 8usize];
        ["Offset of field: tagSQRegFunction::nparamscheck"]
            [::std::mem::offset_of!(tagSQRegFunction, nparamscheck) - 16usize];
        ["Offset of field: tagSQRegFunction::typemask"]
            [::std::mem::offset_of!(tagSQRegFunction, typemask) - 24usize];
    };
    pub type SQRegFunction = root::tagSQRegFunction;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct tagSQFunctionInfo {
        pub funcid: root::SQUserPointer,
        pub name: *const root::SQChar,
        pub source: *const root::SQChar,
        pub line: root::SQInteger,
    }
    #[allow(clippy::unnecessary_operation, clippy::identity_op)]
    const _: () = {
        ["Size of tagSQFunctionInfo"][::std::mem::size_of::<tagSQFunctionInfo>() - 32usize];
        ["Alignment of tagSQFunctionInfo"][::std::mem::align_of::<tagSQFunctionInfo>() - 8usize];
        ["Offset of field: tagSQFunctionInfo::funcid"]
            [::std::mem::offset_of!(tagSQFunctionInfo, funcid) - 0usize];
        ["Offset of field: tagSQFunctionInfo::name"]
            [::std::mem::offset_of!(tagSQFunctionInfo, name) - 8usize];
        ["Offset of field: tagSQFunctionInfo::source"]
            [::std::mem::offset_of!(tagSQFunctionInfo, source) - 16usize];
        ["Offset of field: tagSQFunctionInfo::line"]
            [::std::mem::offset_of!(tagSQFunctionInfo, line) - 24usize];
    };
    pub type SQFunctionInfo = root::tagSQFunctionInfo;
    unsafe extern "C" {
        pub fn sq_open(initialstacksize: root::SQInteger) -> root::HSQUIRRELVM;
    }
    unsafe extern "C" {
        pub fn sq_newthread(
            friendvm: root::HSQUIRRELVM,
            initialstacksize: root::SQInteger,
        ) -> root::HSQUIRRELVM;
    }
    unsafe extern "C" {
        pub fn sq_seterrorhandler(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_close(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_setforeignptr(v: root::HSQUIRRELVM, p: root::SQUserPointer);
    }
    unsafe extern "C" {
        pub fn sq_getforeignptr(v: root::HSQUIRRELVM) -> root::SQUserPointer;
    }
    unsafe extern "C" {
        pub fn sq_setsharedforeignptr(v: root::HSQUIRRELVM, p: root::SQUserPointer);
    }
    unsafe extern "C" {
        pub fn sq_getsharedforeignptr(v: root::HSQUIRRELVM) -> root::SQUserPointer;
    }
    unsafe extern "C" {
        pub fn sq_setvmreleasehook(v: root::HSQUIRRELVM, hook: root::SQRELEASEHOOK);
    }
    unsafe extern "C" {
        pub fn sq_getvmreleasehook(v: root::HSQUIRRELVM) -> root::SQRELEASEHOOK;
    }
    unsafe extern "C" {
        pub fn sq_setsharedreleasehook(v: root::HSQUIRRELVM, hook: root::SQRELEASEHOOK);
    }
    unsafe extern "C" {
        pub fn sq_getsharedreleasehook(v: root::HSQUIRRELVM) -> root::SQRELEASEHOOK;
    }
    unsafe extern "C" {
        pub fn sq_setprintfunc(
            v: root::HSQUIRRELVM,
            printfunc: root::SQPRINTFUNCTION,
            errfunc: root::SQPRINTFUNCTION,
        );
    }
    unsafe extern "C" {
        pub fn sq_getprintfunc(v: root::HSQUIRRELVM) -> root::SQPRINTFUNCTION;
    }
    unsafe extern "C" {
        pub fn sq_geterrorfunc(v: root::HSQUIRRELVM) -> root::SQPRINTFUNCTION;
    }
    unsafe extern "C" {
        pub fn sq_suspendvm(v: root::HSQUIRRELVM) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_wakeupvm(
            v: root::HSQUIRRELVM,
            resumedret: root::SQBool,
            retval: root::SQBool,
            raiseerror: root::SQBool,
            throwerror: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getvmstate(v: root::HSQUIRRELVM) -> root::SQInteger;
    }
    unsafe extern "C" {
        pub fn sq_getversion() -> root::SQInteger;
    }
    unsafe extern "C" {
        pub fn sq_compile(
            v: root::HSQUIRRELVM,
            read: root::SQLEXREADFUNC,
            p: root::SQUserPointer,
            sourcename: *const root::SQChar,
            raiseerror: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_compilebuffer(
            v: root::HSQUIRRELVM,
            s: *const root::SQChar,
            size: root::SQInteger,
            sourcename: *const root::SQChar,
            raiseerror: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_enabledebuginfo(v: root::HSQUIRRELVM, enable: root::SQBool);
    }
    unsafe extern "C" {
        pub fn sq_notifyallexceptions(v: root::HSQUIRRELVM, enable: root::SQBool);
    }
    unsafe extern "C" {
        pub fn sq_setcompilererrorhandler(v: root::HSQUIRRELVM, f: root::SQCOMPILERERROR);
    }
    unsafe extern "C" {
        pub fn sq_push(v: root::HSQUIRRELVM, idx: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_pop(v: root::HSQUIRRELVM, nelemstopop: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_poptop(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_remove(v: root::HSQUIRRELVM, idx: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_gettop(v: root::HSQUIRRELVM) -> root::SQInteger;
    }
    unsafe extern "C" {
        pub fn sq_settop(v: root::HSQUIRRELVM, newtop: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_reservestack(v: root::HSQUIRRELVM, nsize: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_cmp(v: root::HSQUIRRELVM) -> root::SQInteger;
    }
    unsafe extern "C" {
        pub fn sq_move(dest: root::HSQUIRRELVM, src: root::HSQUIRRELVM, idx: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_newuserdata(
            v: root::HSQUIRRELVM,
            size: root::SQUnsignedInteger,
        ) -> root::SQUserPointer;
    }
    unsafe extern "C" {
        pub fn sq_newtable(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_newtableex(v: root::HSQUIRRELVM, initialcapacity: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_newarray(v: root::HSQUIRRELVM, size: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_newclosure(
            v: root::HSQUIRRELVM,
            func: root::SQFUNCTION,
            nfreevars: root::SQUnsignedInteger,
        );
    }
    unsafe extern "C" {
        pub fn sq_setparamscheck(
            v: root::HSQUIRRELVM,
            nparamscheck: root::SQInteger,
            typemask: *const root::SQChar,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_bindenv(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setclosureroot(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getclosureroot(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_pushstring(v: root::HSQUIRRELVM, s: *const root::SQChar, len: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_pushfloat(v: root::HSQUIRRELVM, f: root::SQFloat);
    }
    unsafe extern "C" {
        pub fn sq_pushinteger(v: root::HSQUIRRELVM, n: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_pushbool(v: root::HSQUIRRELVM, b: root::SQBool);
    }
    unsafe extern "C" {
        pub fn sq_pushuserpointer(v: root::HSQUIRRELVM, p: root::SQUserPointer);
    }
    unsafe extern "C" {
        pub fn sq_pushnull(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_pushthread(v: root::HSQUIRRELVM, thread: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_gettype(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQObjectType;
    }
    unsafe extern "C" {
        pub fn sq_typeof(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getsize(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQInteger;
    }
    unsafe extern "C" {
        pub fn sq_gethash(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQHash;
    }
    unsafe extern "C" {
        pub fn sq_getbase(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_instanceof(v: root::HSQUIRRELVM) -> root::SQBool;
    }
    unsafe extern "C" {
        pub fn sq_tostring(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_tobool(v: root::HSQUIRRELVM, idx: root::SQInteger, b: *mut root::SQBool);
    }
    unsafe extern "C" {
        pub fn sq_getstringandsize(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            c: *mut *const root::SQChar,
            size: *mut root::SQInteger,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getstring(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            c: *mut *const root::SQChar,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getinteger(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            i: *mut root::SQInteger,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getfloat(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            f: *mut root::SQFloat,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getbool(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            b: *mut root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getthread(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            thread: *mut root::HSQUIRRELVM,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getuserpointer(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            p: *mut root::SQUserPointer,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getuserdata(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            p: *mut root::SQUserPointer,
            typetag: *mut root::SQUserPointer,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_settypetag(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            typetag: root::SQUserPointer,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_gettypetag(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            typetag: *mut root::SQUserPointer,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setreleasehook(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            hook: root::SQRELEASEHOOK,
        );
    }
    unsafe extern "C" {
        pub fn sq_getreleasehook(v: root::HSQUIRRELVM, idx: root::SQInteger)
        -> root::SQRELEASEHOOK;
    }
    unsafe extern "C" {
        pub fn sq_getscratchpad(
            v: root::HSQUIRRELVM,
            minsize: root::SQInteger,
        ) -> *mut root::SQChar;
    }
    unsafe extern "C" {
        pub fn sq_getfunctioninfo(
            v: root::HSQUIRRELVM,
            level: root::SQInteger,
            fi: *mut root::SQFunctionInfo,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getclosureinfo(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            nparams: *mut root::SQInteger,
            nfreevars: *mut root::SQInteger,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getclosurename(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setnativeclosurename(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            name: *const root::SQChar,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setinstanceup(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            p: root::SQUserPointer,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getinstanceup(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            p: *mut root::SQUserPointer,
            typetag: root::SQUserPointer,
            throwerror: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setclassudsize(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            udsize: root::SQInteger,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_newclass(v: root::HSQUIRRELVM, hasbase: root::SQBool) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_createinstance(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setattributes(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getattributes(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getclass(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_weakref(v: root::HSQUIRRELVM, idx: root::SQInteger);
    }
    unsafe extern "C" {
        pub fn sq_getdefaultdelegate(v: root::HSQUIRRELVM, t: root::SQObjectType)
        -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getmemberhandle(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            handle: *mut root::HSQMEMBERHANDLE,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getbyhandle(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            handle: *const root::HSQMEMBERHANDLE,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setbyhandle(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            handle: *const root::HSQMEMBERHANDLE,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_pushroottable(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_pushregistrytable(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_pushconsttable(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_setroottable(v: root::HSQUIRRELVM) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setconsttable(v: root::HSQUIRRELVM) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_newslot(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            bstatic: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_deleteslot(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            pushval: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_set(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_get(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_rawget(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_rawset(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_rawdeleteslot(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            pushval: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_newmember(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            bstatic: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_rawnewmember(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            bstatic: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_arrayappend(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_arraypop(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            pushval: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_arrayresize(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            newsize: root::SQInteger,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_arrayreverse(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_arrayremove(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            itemidx: root::SQInteger,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_arrayinsert(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            destpos: root::SQInteger,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setdelegate(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getdelegate(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_clone(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setfreevariable(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            nval: root::SQUnsignedInteger,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_next(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getweakrefval(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_clear(v: root::HSQUIRRELVM, idx: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_call(
            v: root::HSQUIRRELVM,
            params: root::SQInteger,
            retval: root::SQBool,
            raiseerror: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_resume(
            v: root::HSQUIRRELVM,
            retval: root::SQBool,
            raiseerror: root::SQBool,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getlocal(
            v: root::HSQUIRRELVM,
            level: root::SQUnsignedInteger,
            idx: root::SQUnsignedInteger,
        ) -> *const root::SQChar;
    }
    unsafe extern "C" {
        pub fn sq_getcallee(v: root::HSQUIRRELVM) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getfreevariable(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            nval: root::SQUnsignedInteger,
        ) -> *const root::SQChar;
    }
    unsafe extern "C" {
        pub fn sq_throwerror(v: root::HSQUIRRELVM, err: *const root::SQChar) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_throwobject(v: root::HSQUIRRELVM) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_reseterror(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_getlasterror(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_tailcall(v: root::HSQUIRRELVM, nparams: root::SQInteger) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getstackobj(
            v: root::HSQUIRRELVM,
            idx: root::SQInteger,
            po: *mut root::HSQOBJECT,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_pushobject(v: root::HSQUIRRELVM, obj: root::HSQOBJECT);
    }
    unsafe extern "C" {
        pub fn sq_addref(v: root::HSQUIRRELVM, po: *mut root::HSQOBJECT);
    }
    unsafe extern "C" {
        pub fn sq_release(v: root::HSQUIRRELVM, po: *mut root::HSQOBJECT) -> root::SQBool;
    }
    unsafe extern "C" {
        pub fn sq_getrefcount(
            v: root::HSQUIRRELVM,
            po: *mut root::HSQOBJECT,
        ) -> root::SQUnsignedInteger;
    }
    unsafe extern "C" {
        pub fn sq_resetobject(po: *mut root::HSQOBJECT);
    }
    unsafe extern "C" {
        pub fn sq_objtostring(o: *const root::HSQOBJECT) -> *const root::SQChar;
    }
    unsafe extern "C" {
        pub fn sq_objtobool(o: *const root::HSQOBJECT) -> root::SQBool;
    }
    unsafe extern "C" {
        pub fn sq_objtointeger(o: *const root::HSQOBJECT) -> root::SQInteger;
    }
    unsafe extern "C" {
        pub fn sq_objtofloat(o: *const root::HSQOBJECT) -> root::SQFloat;
    }
    unsafe extern "C" {
        pub fn sq_objtouserpointer(o: *const root::HSQOBJECT) -> root::SQUserPointer;
    }
    unsafe extern "C" {
        pub fn sq_getobjtypetag(
            o: *const root::HSQOBJECT,
            typetag: *mut root::SQUserPointer,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_getvmrefcount(
            v: root::HSQUIRRELVM,
            po: *const root::HSQOBJECT,
        ) -> root::SQUnsignedInteger;
    }
    unsafe extern "C" {
        pub fn sq_collectgarbage(v: root::HSQUIRRELVM) -> root::SQInteger;
    }
    unsafe extern "C" {
        pub fn sq_resurrectunreachable(v: root::HSQUIRRELVM) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_writeclosure(
            vm: root::HSQUIRRELVM,
            writef: root::SQWRITEFUNC,
            up: root::SQUserPointer,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_readclosure(
            vm: root::HSQUIRRELVM,
            readf: root::SQREADFUNC,
            up: root::SQUserPointer,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_malloc(size: root::SQUnsignedInteger) -> *mut ::std::os::raw::c_void;
    }
    unsafe extern "C" {
        pub fn sq_realloc(
            p: *mut ::std::os::raw::c_void,
            oldsize: root::SQUnsignedInteger,
            newsize: root::SQUnsignedInteger,
        ) -> *mut ::std::os::raw::c_void;
    }
    unsafe extern "C" {
        pub fn sq_free(p: *mut ::std::os::raw::c_void, size: root::SQUnsignedInteger);
    }
    unsafe extern "C" {
        pub fn sq_stackinfos(
            v: root::HSQUIRRELVM,
            level: root::SQInteger,
            si: *mut root::SQStackInfos,
        ) -> root::SQRESULT;
    }
    unsafe extern "C" {
        pub fn sq_setdebughook(v: root::HSQUIRRELVM);
    }
    unsafe extern "C" {
        pub fn sq_setnativedebughook(v: root::HSQUIRRELVM, hook: root::SQDEBUGHOOK);
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct SQWeakRef {
        pub _address: u8,
    }
}
